from __future__ import annotations

import random

DEFAULT_GRID_SIZE = 64
ROTATE_IMAGE_K = 0

# EA configuration defaults
POPULATION_SIZE = 64
GENERATIONS = 50
CROSSOVER_RATE = 0.8
MUTATION_RATE = 0.3
TOURNAMENT_K = 3
ELITE_FRACTION = 0.05
RANDOM_SEED = random.randint(0, 1_000_000)


QUADRANT_WEIGHT = 0.9
OVERLAP_WEIGHT = 5.0
AREA_WEIGHT = 4.0
COMPACTNESS_WEIGHT = 3.5
ADJACENCY_WEIGHT = 0.6
LOCATION_WEIGHT = 1.2
SECTION_WEIGHT = 1.5
DISPERSION_WEIGHT = 1.0
ROOM_USAGE_WEIGHT = 1.5
MASK_WEIGHT = 2.0
BUDGET_WEIGHT = 3.0
SECTION_BBOX_WEIGHT = 2.5
REALISM_WEIGHT = 5.0
REALISM_THRESHOLD = 1.0
NO_CHANGE_PENALTY = 1.0
